name: Build

on:
  push:
    branches: [ "main", "feature/aot" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.*

      - name: Build with dotnet
        working-directory: ./LoneBackup.App
        run: dotnet build
